name = "my-s5-node"

# [accounts]
# enabled = false

# [accounts.database]
# path = "data/accounts"

[keypair]
seed = "AUTOMATICALLY_GENERATED_ON_FIRST_START"

[cache] # Caches file objects that are uploaded, streamed or downloaded
path = "/tmp/s5/cache"

[database] # Caches peer and object data (small)
path = "data/hive"

[http.api]
bind = "0.0.0.0"
port = 5522

# [http.api.authorization] 
# bearer_tokens = ["RANDOM_TOKEN"]

[http.api.delete]
enabled = false

[p2p.self.tcp]
ip = "0.0.0.0"
port = 4444

[p2p.peers]
initial = [
  'tcp://z2DWXhEypZqpsEXRY7LjzXCoXeVfP7z8uPUYjeKfnJuJV3A@95.143.172.232:43221', # uber.space
  'tcp://z2DfewUEBF5TnHjMXRyZCQobMirWXJqa3JCeb36UyaHLYhC@116.203.139.40:4444', # hetzner
  'tcp://z2DVNifJx5XhjwQpecQMCZCguum2sAnJNNLfrQmRZt2zxiq@168.119.116.125:4444', # test node
]

[store]
expose = false

[store.local] # Stores file and metadata objects that are uploaded with this node
path = "data/store"

[store.local.http]
bind = "0.0.0.0"
port = 8989
url = "http://localhost:8989"

# [store.arweave]
# gatewayUrl = "http://127.0.0.1:7777"
# walletPath = "/path/to/arweave/walletPath"

# [store.s3] 
# accessKey = "YOUR_ACCESS_KEY"
# bucket = "YOUR_BUCKET_NAME"
# endpoint = "YOUR_S3_ENDPOINT"
# secretKey = "YOUR_SECRET_KEY"

# [store.sia]
# renterd_api_addr = ""
# renterd_api_password = ""
# http = ""
